#!/bin/bash
echo "enter three numbers"
read num1
read num2
read num3
if [ $num1 -gt $num2 -a $num1 -gt $num3 ]
then
echo "$num1 is greater"
elif [ $num2 -gt $num3 ]
then
echo "$num2 is greater"
else
echo "$num3 is greater"
fi


mlm@mlm-H81:~/Desktop/Athira$ chmod +x largest3num.sh
mlm@mlm-H81:~/Desktop/Athira$ ./largest3num.sh
enter three numbers
12
100
13
100 is greater
